name: logisto
description: Приложение для работы со складом и ПВЗ
publish_to: 'none'
version: 1.6.4+53

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  collection: ^1.17.1
  cross_file: ^0.3.3
  dio: ^5.2.1
  drift: ^2.9.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.14.23
  flutter_bluetooth_basic:
    git:
      url: git@github.com:yahya-uddin/flutter_bluetooth_basic.git
      ref: 7ceceec
  flutter_bluetooth_serial:
    git:
      url: git@github.com:rickcasson/flutter_bluetooth_serial.git
      ref: android-12-fixes
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_signature_pad: ^3.0.0
  flutter_typeahead: ^4.7.0
  gs1_barcode_parser: ^1.0.4
  http_parser: ^4.0.2
  iboxpro_flutter: ^1.0.2
  mask_text_input_formatter: ^2.4.0
  package_info_plus: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.0.9
  provider: ^6.0.5
  pub_semver: ^2.1.1
  quiver: ^3.0.1
  sentry_flutter: ^7.7.0
  sqlite3_flutter_libs: ^0.5.0
  u_app_utils:
    git:
      url: git@github.com:Unact/u_app_utils.git
      ref: 47f85d1

dev_dependencies:
  build_runner: ^2.4.5
  drift_dev: ^2.9.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
