name: logisto
description: An application for storage and pickup points employees
publish_to: 'none'
version: 1.2.15+34

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^4.0.4
  device_info_plus: ^4.0.0
  f_logs: ^2.0.0
  fk_user_agent: ^2.1.0
  pub_semver: ^2.1.1
  path_provider: ^2.0.9
  package_info_plus: ^1.4.0
  sentry_flutter: ^6.11.1
  url_launcher: ^6.0.20
  flutter_bloc: ^8.0.1
  flutter_blue_plus: ^1.3.0
  flutter_signature_pad: ^3.0.0
  iboxpro_flutter: ^1.0.2
  flutter_bluetooth_serial:
    git:
      url: git@github.com:rickcasson/flutter_bluetooth_serial.git
      ref: android-12-fixes
  quiver: ^3.0.1
  drift: ^1.5.0
  qr_code_scanner: ^1.0.1
  sqlite3_flutter_libs: ^0.5.0
  soundpool: ^2.3.0
  camera: ^0.9.4
  permission_handler: ^10.2.0
  cupertino_icons: ^1.0.0
  flutter_typeahead: ^4.0.0
  equatable: ^2.0.5
  windows1251: ^1.0.2
  flutter_bluetooth_basic:
    git:
      url: git@github.com:yahya-uddin/flutter_bluetooth_basic.git
      ref: 7ceceec

dev_dependencies:
  drift_dev: ^1.5.2
  build_runner: ^2.1.8
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/beep.mp3
