name: logisto
description: An application for storage and pickup points employees
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^4.0.0
  device_info_plus: ^1.0.1
  f_logs: ^2.0.0
  fk_user_agent: ^2.0.1
  pub_semver: ^2.0.0
  sqflite: ^2.0.0
  path_provider: ^2.0.2
  package_info: ^2.0.2
  sentry_flutter: ^6.2.2
  url_launcher: ^6.0.6
  flutter_bloc: ^8.0.0
  flutter_blue: ^0.8.0
  flutter_signature_pad: ^3.0.0
  iboxpro_flutter: ^1.0.2
  flutter_bluetooth_serial: ^0.4.0
  quiver: ^3.0.1
  drift: ^1.1.1
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.8.0

dev_dependencies:
  drift_dev: ^1.1.1
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
